### ISSUE TITLE
Python version of jrun does not parse GAVs as expected

### ISSUE THREAD

**Issue by ctrueden** [ctrueden/jrun#16]
With no prior existing `~/.jrun` folder:

```
$ python jrun net.imagej:imagej:2.0.0-rc-67
INFO 2018-09-25 16:47:47,780: Failed to bootstrap the artifact.
INFO 2018-09-25 16:47:47,781:
INFO 2018-09-25 16:47:47,781: Possible solutions:
INFO 2018-09-25 16:47:47,781: * Double check the endpoint for correctness (https://search.maven.org/).
INFO 2018-09-25 16:47:47,781: * Add needed repositories to ~/.jrunrc [repositories] block (see README).
INFO 2018-09-25 16:47:47,781: * Try with an explicit version number (release metadata might be wrong).

ERROR 2018-09-25 16:47:47,781: Error in ('/usr/local/bin/mvn', '-B', '-f', '/Users/curtis/.jrun/net/imagej/net.imagej/imagej/pom.xml', 'dependency:resolve'): Command '('/usr/local/bin/mvn', '-B', '-f', '/Users/curtis/.jrun/net/imagej/net.imagej/imagej/pom.xml', 'dependency:resolve')' returned non-zero exit status 1.
```

The issue appears to stem from the generated `pom.xml`:

```
$ xmllint --format /Users/curtis/.jrun/net/imagej/net.imagej/imagej/pom.xml
<?xml version="1.0"?>
<project>
	<modelVersion>4.0.0</modelVersion>
	<groupId>net.imagej-BOOTSTRAPPER</groupId>
	<artifactId>net.imagej-BOOTSTRAPPER</artifactId>
	<version>0</version>
	<dependencyManagement>
		<dependencies/>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>net.imagej</groupId>
			<artifactId>net.imagej</artifactId>
			<version>imagej</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>imagej.public</id>
			<url>https://maven.imagej.net/content/groups/public</url>
		</repository>
		<repository>
			<id>jitpack</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
</project>
```
Of particular note is the `<dependencies>` block, which lists `net.imagej:net.imagej:imagej` as the artifact, rather than the requested `net.imagej:imagej:2.0.0-rc-67`.

**Comment by ctrueden** [comment]
@hanslovsky I invited you as a collaborator, so that issues like this can be assigned to you directly, if you are willing.

**Comment by hanslovsky** [comment]
I cannot reproduce:
```bash
$ rm -rf ~/.jrun
$ python jrun net.imagej:imagej:2.0.0-rc-67
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

$ ls ~/.jrun/net/imagej/imagej/2.0.0-rc-67 -d
/home/hanslovskyp/.jrun/net/imagej/imagej/2.0.0-rc-67
```
---------------------------
![screenshot_20180927_130412](https://user-images.githubusercontent.com/1086317/46162301-d49f0480-c255-11e8-91d1-a2cb8a08e868.png)
---------------------------
Maybe it is an OSX issue (assuming you are trying on OSX). I will try Windows, as well.

**Comment by ctrueden** [comment]
Yes, I'm on macOS. I'll do some quick debugging to gather some more details.

**Comment by hanslovsky** [comment]
Can you run `jrun` with the `-v` and `-vv` flags, and share the output? The bootstrap pom gets populated with the right G:A:V for me.

**Comment by hanslovsky** [comment]
Just tested on Windows and I was able to run imagej-2.0.0-rc-67

**Comment by ctrueden** [comment]
OK, I believe the problem is this line in my `.jrunrc`:
```
imagej = net.imagej:imagej
```
This is one of the example shortcuts given in the README.

I think what's happening is that the `imagej` artifactId is being expanded to `net.imagej:imagej`, so the original `net.imagej:imagej:2.0.0-rc-67` becomes `net.imagej:net.imagej:imagej:2.0.0-rc-67`. The shell script does not suffer from this behavior because IIRC, it only does shortcut expansion at the beginning of a particular GAV coordinate.

**Comment by hanslovsky** [comment]
:+1: I can restrict to only a single round of expansion.

**Comment by ctrueden** [comment]
> I can restrict to only a single round of expansion.

The problem isn't multiple passes though, is it? Only that for the string `net.imagej:imagej:2.0.0-rc-67`, the `imagej = net.imagej:imagej` shortcut is being applied once? I didn't dig all the way down to be certain, but from my investigation, it looked like the shortcut was being applied to each component of the endpoint, particularly the artifactId, rather than only matches at the beginning of the entire endpoint string. Did I misunderstand?

**Comment by hanslovsky** [comment]
Yes, you are correct. the shortcut expansion is applied to each component of a coordinate. If it is to be applied to the first component only, the fix will be easy. Something like this should do it:

```python
def expand_coordinate(coordinate, shortcuts={}):
    split = coordinate.split(':')
    return [shortcuts[split[0]] if split in shortcuts else split[0]] + split[1:]
```

**Comment by ctrueden** [comment]
@hanslovsky I think that will be consistent with the behavior described in the README: "Shortcuts are substituted verbatim from the beginning of the endpoint, single-pass in the order they are defined."

**Comment by hanslovsky** [comment]
Yes, my proposed fix would not handle multiple/nested shortcuts. Instead it would replace the first occurrence and return immediately like a bash alias. Adding support for nested aliases would not be hard. My only worry is that understanding why an endpoint is invalid becomes harder for users.

**Comment by hanslovsky** [comment]
I changed `expand_coordinate`:
```python
def expand_coordinate(coordinate, shortcuts={}):
    was_changed = True
    while was_changed:
        matched_shortcut = False
        for shortcut, replacement in shortcuts.items():
            if coordinate.startswith(shortcut):
                _logger.debug("Replacing %s with %s in %s.", shortcut, replacement, coordinate)
                coordinate = coordinate.replace(shortcut, replacement)
                matched_shortcut = True
        was_changed = matched_shortcut
```
With `~/.jrunrc`:
```
[shortcuts]
nij = net.imagej
imagej = nij:imagej
```

 - `imagej:2.0.0-rc-67` gets expanded to `net.imagej:imagej:2.0.0-rc-67`
 - `net.imagej:imagej:2.0.0-rc-67` gets expanded to `net.imagej:imagej:2.0.0-rc-67` (stays the same)

I am happy with this but I have one more question: Should every shortcut be applied once at the most for each coordiante? I.e. if, in a single call to `expand_coordinate`, a coordinate is matched, it cannot applied a second time? This would prevent recursive shortcuts.
