### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by ctrueden** [ctrueden/jrun#7]
### Cygwin

As reported by @imagejan in #6:
> On Windows (cygwin), `jrun` still fails because of symbolic links not being supported by the OS.

Note that Cygwin fakes symlinks, such that Cygwin-based programs will work as expected. However, I expect what is happening here is that `mvn` and/or `java`—not being Cygwin-based—do not have proper support for the fake symlinks.

One way to fix this would be to improve the `jrun` script to use [`mklink`](https://www.sevenforums.com/tutorials/278262-mklink-create-use-links-windows.html) instead on Windows. IIRC, older FAT file systems do not support Windows links or junctions, but NTFS does.

### Windows Subsystem for Linux

It would be ideal to make `jrun` work on Windows also via the [new built-in bash feature](https://superuser.com/a/1059340/412420). I've heard that although it's still beta, bash on Windows works very well for lots of things—although running programs which need X requires [Xming](https://superuser.com/a/1059340/412420). I'm not sure about Windows GUI programs like `javaw.exe` though.

**Comment by ctrueden** [comment]
@imagejan As a workaround for now, could you please test the `windows` branch in Cygwin? I changed it so that it should do `cp` instead of `ln -s` for now.

Could you also please try changing the `cp` in the `doLink` method to do `ln` (without the `-s`) instead? You'll need to launch jrun with the `-u` flag each time to regenerate the endpoint cache.

If `ln` succeeds in making a hard link, we should probably just use `ln` always. This would not only work on Windows, but would also avoid problems on *nix where the `~/.m2/repository` is purged and causes all `jrun` endpoints to stop working.

**Comment by imagejan** [comment]
I was lying, as I'm running MINGW64, not Cygwin, with my Git Bash installation.
So I replaced `CYGWIN` by `MINGW` in the `isWindows` function.

Then I still get an error, probably caused by the fact that MINGW64 uses `/c/cygwin/home/<username>/` as a user directory, but my local `.m2` directory is in `C:\Users\<username>\.m2`:

```
cp: cannot stat '/c/cygwin/home/eglijan/.m2/repository/org/python/jython-standalone/2.7.1b3/jython-standalone-2.7.1b3.jar': No such file or directory
```

and the same when changing `cp` to `ln`:

```
ln: failed to access '/c/cygwin/home/eglijan/.m2/repository/org/python/jython-standalone/2.7.1b3/jython-standalone-2.7.1b3.jar': No such file or directory
```

I also wanted to try the "Ubuntu bash on Windows" on a Windows 10 machine, but after creating the very basic root environment (which works fine), anything else requiring downloads fails because of proxy issues in our restrictive network...

Will have to continue testing this later...

**Comment by ctrueden** [comment]
@imagejan Thanks for testing. I am currently ironing out a bunch of Cygwin-related problems. I will also try with MinGW via Git Bash, and ensure that works too. Stay tuned.

**Comment by imagejan** [comment]
Well, adding:

```
[settings]
m2Repo = /c/Users/eglijan/.m2/repository
```

to my `.jrunrc` got me one step further. Now, running `./jrun -v -u org.python:jython-standalone`, I get:

```
++ unzip -p /c/cygwin/home/eglijan/.jrun/org.python/jython-standalone/jython-standalone-2.7.1b3.jar META-INF/MANIFEST.MF
[INFO] Inferred main class: org.python.util.jython
+ java -cp '/c/cygwin/home/eglijan/.jrun/org.python/jython-standalone/*' org.python.util.jython
Error: Could not find or load main class org.python.util.jython
```

**Comment by ctrueden** [comment]
Yeah, both mvn and java need Windows-style paths. I am adjusting for that in the script itself. I'll ping back when it's working.

**Comment by ctrueden** [comment]
It should work in Cygwin now. I did not yet test the MinGW bash shell, nor the bash from Windows Subsystem for Linux, since I was unable to install the latter in my Windows 10 VM.

Please report back with success or failure when you get a chance.

**Comment by ctrueden** [comment]
@imagejan Any word on whether the script works on your Windows systems?

**Comment by imagejan** [comment]
I get the following output (with Git Bash, MINGW64), but then nothing happens:

```
[INFO] Artifact:
[INFO] - groupId    = net.imagej
[INFO] - artifactId = imagej
[INFO] - version    = RELEASE
[INFO] - classifier = <none>
[INFO] Workspace = /c/cygwin/home/eglijan/.jrun/net.imagej/imagej
```

I'm not sure it's launching java correctly for me, but there's no further output, and I can only get out by using Ctrl-C.

**Comment by ctrueden** [comment]
> I'm not sure it's launching java correctly for me, but there's no further output, and I can only get out by using Ctrl-C.

<kbd>Ctrl</kbd>+<kbd>Pause</kbd> (i.e. <kbd>Break</kbd>) might tell you more.

I am testing in my Windows 7 VM now.

**Comment by ctrueden** [comment]
> there's no further output, and I can only get out by using Ctrl-C.

Finally got Git Bash up and running on my Windows VM, and replicated the behavior you are seeing. (It works in Cygwin.)

The problem, which you can see if you put `set -x` at the top of the `jrun` script, is the call to `cmd /c cd`, which hangs. Here is the source in question, which illustrates the irony here:
```bash
goodPath() {
	# NB: Non-Cygwin Windows programs, including mvn and java,
	# do not understand the Cygwin-specific '/' prefix. They need
	# absolute paths to begin with a drive letter (e.g., 'C:').
	if [ "$(isWindows)" ]
	then
		# NB: Advice online is to use the cygpath command for
		# converting from *nix to Windows paths. However, I
		# want to ensure this also works in other *nix-like
		# environments, particularly MinGW / MSYS / Git Bash.
		(
			cd "$(dirname "$1")" &&
			dir=$(cmd /c cd)
			# HACK: Windows commands emit a trailing \r.
			dir=${dir%?}
			echo "$dir\\$(basename "$1")"
		)
	else
		echo "$1"
	fi
}
```

I used `cmd /c cd` specifically so that Git Bash _would_ work instead of requiring Cygwin. But in practice, no dice.

**Comment by ctrueden** [comment]
It turns out that msys2 ships `cygpath` already. So we can just use it.

In my hands, jrun now works using either Cygwin or Git Bash.
