### ISSUE TITLE
Invalid cross-device link / Could not find or load main class

### ISSUE THREAD

**Issue by eitch** [ctrueden/jrun#8]
I'm trying to run my project:

    jrun -v -u li.strolch:li.strolch.agent:1.5.0-SNAPSHOT:li.strolch.runtime.main.MainStarter

Sadly it fails:

    [INFO] Artifact:
    [INFO] - groupId    = li.strolch
    [INFO] - artifactId = li.strolch.agent
    [INFO] - version    = 1.5.0-SNAPSHOT
    [INFO] - classifier = <none>
    [INFO] Workspace = /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ++ mvn -f /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/pom.xml dependency:resolve
    + ln /home/eitch/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/slf4j-api-1.7.25.jar' => '/home/eitch/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/gson-2.8.0.jar' => '/home/eitch/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/commons-cli-1.4.jar' => '/home/eitch/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/li/strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.agent-1.5.0-SNAPSHOT.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/li.strolch.agent-1.5.0-SNAPSHOT.jar' => '/home/eitch/.m2/repository/li/strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.agent-1.5.0-SNAPSHOT.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/javax/mail/javax.mail-api/1.5.6/javax.mail-api-1.5.6.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/javax.mail-api-1.5.6.jar' => '/home/eitch/.m2/repository/javax/mail/javax.mail-api/1.5.6/javax.mail-api-1.5.6.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/activation-1.1.jar' => '/home/eitch/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/li/strolch/li.strolch.utils/1.5.0-SNAPSHOT/li.strolch.utils-1.5.0-SNAPSHOT.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/li.strolch.utils-1.5.0-SNAPSHOT.jar' => '/home/eitch/.m2/repository/li/strolch/li.strolch.utils/1.5.0-SNAPSHOT/li.strolch.utils-1.5.0-SNAPSHOT.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/li/strolch/li.strolch.model/1.5.0-SNAPSHOT/li.strolch.model-1.5.0-SNAPSHOT.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/li.strolch.model-1.5.0-SNAPSHOT.jar' => '/home/eitch/.m2/repository/li/strolch/li.strolch.model/1.5.0-SNAPSHOT/li.strolch.model-1.5.0-SNAPSHOT.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/li/strolch/li.strolch.privilege/1.5.0-SNAPSHOT/li.strolch.privilege-1.5.0-SNAPSHOT.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/li.strolch.privilege-1.5.0-SNAPSHOT.jar' => '/home/eitch/.m2/repository/li/strolch/li.strolch.privilege/1.5.0-SNAPSHOT/li.strolch.privilege-1.5.0-SNAPSHOT.jar': Invalid cross-device link
    + ln /home/eitch/.m2/repository/com/sun/mail/javax.mail/1.5.6/javax.mail-1.5.6.jar /home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter
    ln: failed to create hard link '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/javax.mail-1.5.6.jar' => '/home/eitch/.m2/repository/com/sun/mail/javax.mail/1.5.6/javax.mail-1.5.6.jar': Invalid cross-device link
    + java -cp '/home/eitch/.jrun/li.strolch/li.strolch.agent/1.5.0-SNAPSHOT/li.strolch.runtime.main.MainStarter/*' li.strolch.runtime.main.MainStarter
    Error: Could not find or load main class li.strolch.runtime.main.MainStarter

Do you have any idea what is going wrong? If you want to test it, you can download my project and install it using maven:

    git clone https://github.com/4treesCH/strolch.git
    cd strolch
    mvn clean install -DskipTests
    jrun -v -u li.strolch:li.strolch.agent:1.5.0-SNAPSHOT:li.strolch.runtime.main.MainStarter

**Comment by ctrueden** [comment]
`jrun` uses [hard links](https://en.wikipedia.org/wiki/Hard_link) to copy artifacts from `~/.m2/repository` into your endpoint's working directory beneath `~/.jrun`. The error message `Invalid cross-device link` suggests that somehow, your `~/.m2/repository` is mounted on a file system than your home directory in general? What does `df` tell you?

As a workaround, you can change the line:
```bash
ln "$m2Repo/$g/$a/$v/$artName.$p" "$workspace"
```
To:
```bash
ln -s "$m2Repo/$g/$a/$v/$artName.$p" "$workspace"
```
And it will use symlinks instead. `jrun` does not use symlinks by default for the reasons outlined in b78e671c351aa5c3878e7d27a7b7b6c9bbd2aaa4. Alternately, you could change it to `cp` and it will actually copy the files. This will cause `~/.jrun` to take up more disk space, but it will be more resistant to changes in your local Maven repository cache.

The `Could not find or load main class` error is just a consequence of the failed linking—no code gets copied into place, and so Java cannot find it.

I'll update the script to be more defensive about this situation, and produce a nicer error message.

**Comment by eitch** [comment]
Yes, you are right. It works if i use soft links. Maybe test that you can create the hard links and stop if it doesn't work and further allow using symlinks as a configuration? Maybe write this in a config file in ~/.jrun/config ?

**Comment by ctrueden** [comment]
With 8693b3556a61b906ff7a0f1a8f9c77e338cb7d24, `jrun` now falls back to `cp` if `ln` fails.

With ebb00d0f501720f7fac79458c517d8428a26b78d, you can now configure the linking behavior in your `~/.jrunrc`.

Enjoy!

**Comment by eitch** [comment]
Works like a charm!
